Create Emilia - Redone
yourWaifu/is-your-waifu-legal pull request #48
Opened 2020-10-03 23:01 UTC by Alcala09

This is redone so it doesn't replace anybody

2020-10-04 23:43 UTC, yourWaifu commented
can you put the .json to the end, also you don't need to do a pull request just push changes the branch

2020-10-04 23:46 UTC, yourWaifu commented
also I just added the hacktoberfest tag, can you help me make sure it's counting your pull request?

2020-10-05 05:24 UTC, Alcala09 commented
> also I just added the hacktoberfest tag, can you help me make sure it's counting your pull request and how many times it counted?

It has requested for Emilia twice, the second one is the improved one with the changes you requested. For Mai Sakurajima, I do not see her in the main pull request page.

2020-10-06 17:35 UTC, Alcala09 commented
Are there any other issues with the JSON script?

2020-10-08 23:02 UTC, yourWaifu commented
it's not a script, but I'll look over it like usally, I think I need an automated tool for this.

2020-10-08 23:25 UTC, yourWaifu commented
ok here comes the screenshots 
![image](https://user-images.githubusercontent.com/16181109/95522834-31803a00-099b-11eb-8f02-4a540289fc61.png)
![image](https://user-images.githubusercontent.com/16181109/95522873-42c94680-099b-11eb-8314-8521c4b4451a.png)

I'll point out the issues.

2020-10-08 23:26 UTC, yourWaifu requested changes

2020-10-08 23:26 UTC, yourWaifu commented on waifus/emilia.json
> +	"year" : ,
If the year is unknown, remove this line otherwise, it has to be a number.

2020-10-08 23:26 UTC, yourWaifu commented on waifus/mai sakurajima.json
> +	"year" : ,
same goes for this one.

2020-10-09 00:14 UTC, Alcala09 commented on waifus/mai sakurajima.json
> +	"year" : ,
Alright I removed the year lines

2020-10-11 08:53 UTC, yourWaifu commented
more screenshots 
![image](https://user-images.githubusercontent.com/16181109/95674346-a1e6b100-0b7d-11eb-963a-5ad603d4cccc.png)
![image](https://user-images.githubusercontent.com/16181109/95674361-b9259e80-0b7d-11eb-9f81-07d428794cd6.png)

2020-10-11 08:56 UTC, yourWaifu commented
There's a few things I want you to add to the notes, it says that she was frozen at one point, I feel that's an important detail that describes Emilia's age.

2020-10-11 08:58 UTC, yourWaifu requested changes

2020-10-11 08:58 UTC, yourWaifu commented on waifus/emilia.json
> +	"english-name" : "emilia",
Can you make the first letter capital

2020-10-11 08:58 UTC, yourWaifu commented on waifus/mai sakurajima.json
> +	"english-name" : "mai sakurajima",
Same here

2020-10-11 19:14 UTC, Alcala09 commented
Alright made a note about Emilia being frozen for 100 years, and capitalized the names (not for the json)

2020-10-18 01:28 UTC, yourWaifu approved these changes
Looks good

2020-10-18 01:28 UTC, merged